// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	SECRET_KEY: "your-very-secure-secret-key";
	DISCORD_CLIENT_ID: string;
	DISCORD_CLIENT_SECRET: string;
	PLUGIN_BUCKET: R2Bucket;
	DB: D1Database;
}
