// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	JWT_Cache: KVNamespace;
	DISCORD_CLIENT_ID: string;
	DISCORD_CLIENT_SECRET: string;
	SECRET_KEY: string;
	PLUGIN_BUCKET: R2Bucket;
	DB: D1Database;
}
